services:
  app:
    environment:
      - RAILS_ENV=test
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    image: "tkycraft/mahirun:rspec1.0"
    depends_on: {}
    volumes: []
    healthcheck: {}
    entrypoint: []
