FROM ruby:3.2.2-slim-bullseye

WORKDIR /opt/app

RUN \
# install apt package.
	apt-get update \
	&& apt-get install -y \
		build-essential \
		libmagickwand-dev\
# clear apt cache.
	&& apt-get clean -y \
	&& rm -rf /var/lib/apt/lists/* \
# install rails / bundler
	&& gem install rails -v 7.0.4 \
	&& gem install bundler -v 2.4.12

COPY ./ /opt/app/

RUN bundle install

EXPOSE 3000

ENTRYPOINT ["bin/rails", "s", "-b", "0.0.0.0"]
