name: Rspec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      shell: bash
      run: |
        docker compose -f compose.yaml -f compose.rspec.yaml build
    - name: exec rspec
      run:  |
        docker compose -f compose.yaml -f compose.rspec.yaml run app sh entrypoint_test.sh
